### ISSUE TITLE
Missing Ulu's image on Acknowledgements 

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.Rules.Content#585]
Hey @bradystroud 

I noticed this new rule doesn't show Uly's photo: https://www.ssw.com.au/rules/understand-the-power-of-empathy 

<img width="557" alt="Screen Shot 2021-04-15 at 5 28 03 PM" src="https://user-images.githubusercontent.com/12601228/114955441-923c7380-9e11-11eb-8760-7677a160b20a.png">

I assume it is because Uly's profile has a redirect from https://www.ssw.com.au/people/ulysses-maclarem to https://www.ssw.com.au/people/uly and I used the second link in the author section:

```
authors: 
- title: Ulysses MacLaren
  url: https://ssw.com.au/people/uly
```
Of course, I could fix that, but wondering if there is a way to make that URL show the photo too, which would be ideal... 

1. Please action ;)

Cheers,
Tiago

**Comment by bradystroud** [comment]
Hi @tiagov8, 

> 1. Please action ;)

Done - The url is fine, SSW Rules uses the authors title to retrieve the image. Uly's image is broken because of the uppercase 'L' in `- title: Ulysses MacLaren`

If Uly wants to use 'MacLaren' not 'Maclaren', you can follow [the docs](https://github.com/SSWConsulting/SSW.Rules.Content/wiki/How-to-Add-an-Acknowledgment) to add an img field to the author e.g.
```yml
authors:
- title: Ulysses MacLaren
  url: https://ssw.com.au/people/uly
  img: https://github.com/SSWConsulting/SSW.People.Profiles/raw/main/Ulysses-Maclaren/Images/Ulysses-Maclaren-Profile.jpg
```

Thanks,

-Brady
